### ISSUE TITLE
Rebuild SSl certificate for erpnext.com

### ISSUE THREAD

**Issue by raghukamath** [frappe/erpnext_com#161]

**Comment by raghukamath** [comment]
@coding_coffee

**Comment by kennethsequeira** [comment]
@saurabh6790 take this on priority

**Comment by raghukamath** [comment]
The lets encrypt guys have made wild cards available so we should use it now. Chromium will be deprecating our certificates from july 20 2018 and users will see a untrusted page instead

**Comment by saurabh6790** [comment]
Will fix with https://github.com/frappe/central/issues/432
