### ISSUE TITLE
A wrong accounting concept in documentation

### ISSUE THREAD

**Issue by dave-greeko** [frappe/erpnext_com#407]
Hello All, 
First time here and thanks for your work. I started looking into ERPNEXT but with a bumpy start. Anyhow, the documentation related to the accounting module, states: 

> ...Mama invested Rs. 25000 in company, hoping to get some profit. In other words, company is liable to pay Rs. 25000 to Mama in the future. So, account "Mama" is a liability account and it is credited...
> 

Based on the fundamental accounting equation `Assets = Liabilities + Equity` Th The amount of 25000 is an "Equity" not a "Liability" as you stated. In addition, if you look at the expanded accounting equation `Assets = Liabilities + Capital + Net income - Dividends' the 25000 is considered "Capital" 
The entity (Tea Stall) is not **_obliged_** to make (in your case Mama)  as opposed to a bank loan which is Tea Stall's legal financial debts or obligations (Liability)
This is alarming from an accounting point of view.

Regards,
Dave

**Comment by prasadarr** [comment]
reworded
