### ISSUE TITLE
The Search has (again) disappeared from the User Manual - let's put it back.

### ISSUE THREAD

**Issue by vrms** [frappe/erpnext_com#622]
it is an on/off thing apparently.

I believe it is absolutely essential that the documentation can be searched by whatever term. Now there was a Search function, then it was gone, then it came back, and not it is gone again.

So the Search functionality inside the User manual in the [English](https://erpnext.com/docs/user/manual/en), [German](https://erpnext.com/docs/user/manual/de) and [Spanish](https://erpnext.com/docs/user/manual/es) should be reistored (the sooner the better I'd say).

Why is this essential?

1. Without a Search you need to understand the structure of the Software quite a bit in order to know where to manually start searching for a certain article
1. there may be topics missing, and if you can not conduct a search (and likewise quickly note that there is nothing on a certain topic) you may search a long time manually for something that does not even exist. And 
1. if you do not know the structure of the software quite a bit yet you may even manually search content at the completely wrong end of things

all the above is frustrating and will not serve any user and neither the reputation of the project on the whole.

**Comment by vrms** [comment]
has been fixed on a basic level https://github.com/frappe/erpnext_com/pull/641 adds a Search bar for the main page of the manual.

**Comment by vrms** [comment]
seems the Search bar has disappeared again.

**Comment by prasadarr** [comment]
search is available at docs.erpnext.com
